FROM continuumio/miniconda:4.5.4

RUN pip install mlflow \
    && pip install numpy \
    && pip install scipy \
    && pip install pandas \
    && pip install scikit-learn \
    && pip install python-dotenv \
    && pip install boto3 \
    && pip install cloudpickle 
